document.writeln("<script type=\'text/javascript\' src=\'same/jquery-2.0.2.js\'></script>");
document.writeln("	<script type=\'text/javascript\' src=\'same/nav-click.js\'></script>");
document.writeln("	<style type=\'text/css\'>");
document.writeln("		* {");
document.writeln("			margin: 0;");
document.writeln("			padding: 0;");
document.writeln("		}");
document.writeln("		#main {");
document.writeln("			background-color: #f2f2f2;");
document.writeln("			width: 750px;");
document.writeln("		}");
document.writeln("		#navigation {");
document.writeln("			position: fixed;");
document.writeln("			bottom: 0;");
document.writeln("			left: 0;");
document.writeln("			background: linear-gradient(to right,#76dafe,#2fe1a5);");
document.writeln("			width: 100%;");
document.writeln("			height: 98px;");
document.writeln("			z-index: 100;");
document.writeln("		}");
document.writeln("		.nav-bar {");
document.writeln("			width: 630px;");
document.writeln("			height: 88px;");
document.writeln("			margin: 0 auto;");
document.writeln("			margin-top: 10px;");
document.writeln("			display: flex;");
document.writeln("		}");
document.writeln("		.nav-bar li {");
document.writeln("			list-style: none;");
document.writeln("			width: 50px;");
document.writeln("			height: 82px;");
document.writeln("			margin-right: 144px;");
document.writeln("		}");
document.writeln("		.nav-bar li span {");
document.writeln("			display: block;");
document.writeln("			text-align: center;");
document.writeln("			font-size: 22px;");
document.writeln("			color: white;");
document.writeln("			margin-bottom: -15px;");
document.writeln("		}");
document.writeln("	</style>");