document.writeln("<div class=\'isfriend\' style=\'display: none;\'>");
document.writeln("        		<div class=\'friend same\'>");
document.writeln("        		    <img src=\'chat/images/02.png\'><h3>呀！我会发光诶！</h3>");
document.writeln("        		</div>");
document.writeln("        		<div class=\'friend same\'>");
document.writeln("        		    <img src=\'chat/images/03.png\'><h3>嚯嚯嚯</h3>");
document.writeln("        		</div>");
document.writeln("        		<div class=\'friend same\'>");
document.writeln("        		    <img srcfriendimages/01.png\'><h3>嫩你</h3>");
document.writeln("        		</div>");
document.writeln("        		<div class=\'friend same\'>");
document.writeln("        		    <img src=\'chat/images/04.png\'><h3>阔以的噻</h3>");
document.writeln("        		</div>");
document.writeln("        	</div>");