document.writeln("<div class=\'ad\'>");
document.writeln("                    <div class=\'ad-banner\'>");
document.writeln("                        <a href=\'#\'>");
document.writeln("                            <div class=\'ad-banner-slide ad-slide1 ad-slide-active\'></div>");
document.writeln("                        </a>");
document.writeln("                        <a href=\'#\'>");
document.writeln("                            <div class=\'ad-banner-slide ad-slide2\'></div>");
document.writeln("                        </a>");
document.writeln("                        <a href=\'#\'>");
document.writeln("                            <div class=\'ad-banner-slide ad-slide3\'></div>");
document.writeln("                        </a>");
document.writeln("                    </div>");
document.writeln("                    <div class=\'ad-dots\'>");
document.writeln("                        <span class=\'ad-active\'></span>");
document.writeln("                        <span></span>");
document.writeln("                        <span></span>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("                <script type=\'text/javascript\'>              ");
document.writeln("                    var adtimer=null,");
document.writeln("                        adindex=0,");
document.writeln("                        adpics=$(\'.ad-banner div\'),");
document.writeln("                        addots=$(\'.ad-dots span\'),");
document.writeln("                        adsize=adpics.length;");
document.writeln("                    function adstopAutoPlay() {");
document.writeln("                        if(adtimer) clearInterval(adtimer);");
document.writeln("                    }");
document.writeln("                    function adstartAutoPlay() {");
document.writeln("                        adtimer=setInterval(function() {");
document.writeln("                            adindex++;");
document.writeln("                            if(adindex>=adsize) adindex=0;");
document.writeln("                            adchangeImg();");
document.writeln("                        },3000);");
document.writeln("                    }                            ");
document.writeln("                    function adchangeImg() {");
document.writeln("                        for(var i=0,adlen=addots.length;i<adlen;i++) {");
document.writeln("                            addots[i].className=\'\';");
document.writeln("                            adpics[i].style.display=\'none\';");
document.writeln("                        }");
document.writeln("                        addots[adindex].className=\'ad-active\';");
document.writeln("                        adpics[adindex].style.display=\'block\';");
document.writeln("                    }                            ");
document.writeln("                    function adslideImg() {");
document.writeln("                        var banner=$(\'.ad-banner\'),");
document.writeln("                            ad=$(\'.ad\');");
document.writeln("                        ad.onmouseover=function() {");
document.writeln("                            adstopAutoPlay();");
document.writeln("                        }");
document.writeln("                        ad.onmouseout=function() {");
document.writeln("                            adstartAutoPlay();");
document.writeln("                        }");
document.writeln("                        ad.onmouseout();                                ");
document.writeln("                        for(var i=0,len=dots.length;i<len;i++) {");
document.writeln("                            addots[i].id=i;");
document.writeln("                            addots[i].onclick=function() {");
document.writeln("                                adindex=this.id;");
document.writeln("                                adchangeImg();");
document.writeln("                            }");
document.writeln("                        }");
document.writeln("                    }");
document.writeln("                    adslideImg();");
document.writeln("                </script>");